INSERT INTO public.hostels (name, slug, description, address, distance_from_campus, price_min, price_max, gender, amenities, is_verified) VALUES
('Sri Sai Hostel', 'sri-sai-hostel', 'Well-maintained hostel with spacious rooms and good food quality. Located close to KL University main gate.', 'Vaddeswaram, Green Fields', 0.5, 6000, 8000, 'male', ARRAY['WiFi','AC','Laundry','Gym','Mess'], true),
('Lakshmi Residency', 'lakshmi-residency', 'Premium girls hostel with 24/7 security, CCTV, and home-cooked meals.', 'Near KLU Back Gate, Vaddeswaram', 0.8, 7000, 10000, 'female', ARRAY['WiFi','AC','CCTV','Mess','Hot Water','Study Room'], true),
('Star Boys Hostel', 'star-boys-hostel', 'Budget-friendly hostel ideal for students looking for affordable accommodation near campus.', 'Main Road, Vaddeswaram', 1.2, 4000, 6000, 'male', ARRAY['WiFi','Fan','Mess','Parking'], true),
('Green Valley PG', 'green-valley-pg', 'Modern co-ed PG with individual rooms and attached bathrooms.', 'Kanuru Road, Vijayawada', 3.5, 8000, 12000, 'co-ed', ARRAY['WiFi','AC','Attached Bath','Kitchen','Laundry'], true),
('KLU Elite Hostel', 'klu-elite-hostel', 'Premium hostel with single occupancy rooms, study tables, and recreation area.', 'Beside KLU Campus, Vaddeswaram', 0.3, 9000, 14000, 'male', ARRAY['WiFi','AC','Gym','Recreation','Mess','Laundry','Study Room'], true),
('Priya Girls Hostel', 'priya-girls-hostel', 'Safe and secure hostel for girls with warden, mess, and regular cleaning.', 'Main Road, Vaddeswaram', 1.0, 5000, 7500, 'female', ARRAY['WiFi','Fan','Mess','CCTV','Hot Water'], true),
('Royal Residency PG', 'royal-residency-pg', 'Luxurious PG accommodation with fully furnished rooms and daily housekeeping.', 'Mangalagiri Road', 4.0, 10000, 16000, 'co-ed', ARRAY['WiFi','AC','Attached Bath','Kitchen','TV','Parking','Laundry'], false),
('Campus View Hostel', 'campus-view-hostel', 'Budget hostel with a campus view, basic amenities, and friendly environment.', 'Vaddeswaram Village', 1.5, 3500, 5500, 'male', ARRAY['WiFi','Fan','Mess','Parking'], false);
